date.timezone = UTC
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On

memory_limit = 256M
upload_max_filesize = 8M
post_max_size = 8M

session.use_strict_mode = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax

opcache.enable = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
